jobs:
  - name: test_tag_release
    type: runSh
    steps:
      - IN: test_tag_release_gr
      - TASK:
        - script: echo "hello"
        
resources:
  - name: test_tag_release_gr
    type: gitRepo
    integration: github-manishas
    pointer:
      sourceName: manishas/test-runsh-tag-release
      buildOnCommit: true
      buildOnTagPush: true
      buildOnRelease: true
      
  - name: test_tag_release_gr1
    type: gitRepo
    integration: github-manishas
    pointer:
      sourceName: manishas/test-runsh-tag-release
      buildOnCommit: true
      buildOnTagPush: true
      buildOnRelease: true      
      
